dist: trusty
sudo: no

language: python

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

cache: pip

services:
  - redis-server

env:
  - TOXENV=flake8
  - TOXENV=isort

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-1.8-sqlite
    - python: 2.7
      env: TOXENV=py27-1.8-postgresql
    - python: 2.7
      env: TOXENV=py27-1.8-postgis
    - python: 2.7
      env: TOXENV=py27-1.9-sqlite
    - python: 2.7
      env: TOXENV=py27-1.9-postgresql
    - python: 2.7
      env: TOXENV=py27-1.9-postgis
    - python: 2.7
      env: TOXENV=py27-1.10-sqlite
    - python: 2.7
      env: TOXENV=py27-1.10-postgresql
    - python: 2.7
      env: TOXENV=py27-1.10-postgis
    - python: 2.7
      env: TOXENV=py27-1.11-sqlite
    - python: 2.7
      env: TOXENV=py27-1.11-postgresql
    - python: 2.7
      env: TOXENV=py27-1.11-postgis

    - python: 3.4
      env: TOXENV=py34-1.8-sqlite
    - python: 3.4
      env: TOXENV=py34-1.8-postgresql
    - python: 3.4
      env: TOXENV=py34-1.8-postgis
    - python: 3.4
      env: TOXENV=py34-1.9-sqlite
    - python: 3.4
      env: TOXENV=py34-1.9-postgresql
    - python: 3.4
      env: TOXENV=py34-1.9-postgis
    - python: 3.4
      env: TOXENV=py34-1.10-sqlite
    - python: 3.4
      env: TOXENV=py34-1.10-postgresql
    - python: 3.4
      env: TOXENV=py34-1.10-postgis
    - python: 3.4
      env: TOXENV=py34-1.11-sqlite
    - python: 3.4
      env: TOXENV=py34-1.11-postgresql
    - python: 3.4
      env: TOXENV=py34-1.11-postgis
    - python: 3.4
      env: TOXENV=py34-2.0-sqlite
    - python: 3.4
      env: TOXENV=py34-2.0-postgresql
    - python: 3.4
      env: TOXENV=py34-2.0-postgis

    - python: 3.5
      env: TOXENV=py35-1.8-sqlite
    - python: 3.5
      env: TOXENV=py35-1.8-postgresql
    - python: 3.5
      env: TOXENV=py35-1.8-postgis
    - python: 3.5
      env: TOXENV=py35-1.9-sqlite
    - python: 3.5
      env: TOXENV=py35-1.9-postgresql
    - python: 3.5
      env: TOXENV=py35-1.9-postgis
    - python: 3.5
      env: TOXENV=py35-1.10-sqlite
    - python: 3.5
      env: TOXENV=py35-1.10-postgresql
    - python: 3.5
      env: TOXENV=py35-1.10-postgis
    - python: 3.5
      env: TOXENV=py35-1.11-sqlite
    - python: 3.5
      env: TOXENV=py35-1.11-postgresql
    - python: 3.5
      env: TOXENV=py35-1.11-postgis
    - python: 3.5
      env: TOXENV=py35-2.0-sqlite
    - python: 3.5
      env: TOXENV=py35-2.0-postgresql
    - python: 3.5
      env: TOXENV=py35-2.0-postgis
    - python: 3.5
      env: TOXENV=py35-master-sqlite
    - python: 3.5
      env: TOXENV=py35-master-postgresql
    - python: 3.5
      env: TOXENV=py35-master-postgis

    - python: 3.6
      env: TOXENV=py36-1.11-sqlite
    - python: 3.6
      env: TOXENV=py36-1.11-postgresql
    - python: 3.6
      env: TOXENV=py36-1.11-postgis
    - python: 3.6
      env: TOXENV=py36-2.0-sqlite
    - python: 3.6
      env: TOXENV=py36-2.0-postgresql
    - python: 3.6
      env: TOXENV=py36-2.0-postgis
    - python: 3.6
      env: TOXENV=py36-master-sqlite
    - python: 3.6
      env: TOXENV=py36-master-postgresql
    - python: 3.6
      env: TOXENV=py36-master-postgis
  allow_failures:
    - env: TOXENV=py34-2.0-sqlite
    - env: TOXENV=py34-2.0-postgresql
    - env: TOXENV=py34-2.0-postgis
    - env: TOXENV=py35-2.0-sqlite
    - env: TOXENV=py35-2.0-postgresql
    - env: TOXENV=py35-2.0-postgis
    - env: TOXENV=py36-2.0-sqlite
    - env: TOXENV=py36-2.0-postgresql
    - env: TOXENV=py36-2.0-postgis
    - env: TOXENV=py35-master-sqlite
    - env: TOXENV=py35-master-postgresql
    - env: TOXENV=py35-master-postgis
    - env: TOXENV=py36-master-sqlite
    - env: TOXENV=py36-master-postgresql
    - env: TOXENV=py36-master-postgis

install:
  - pip install tox coveralls

before_script:
  - if echo $TOXENV | grep -E '(-postgresql|-postgis)' -q; then psql -U postgres -c "CREATE DATABASE mutant;"; fi
  - if echo $TOXENV | grep '\-postgis' -q; then psql mutant -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"; fi

script:
  - tox

after_success:
  - coveralls
