sudo: no

language: python

addons:
  postgresql: "9.3"

services:
  - redis-server

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.8-sqlite
  - TOXENV=py27-1.8-postgresql
  - TOXENV=py27-1.8-postgis
  - TOXENV=py27-1.9-sqlite
  - TOXENV=py27-1.9-postgresql
  - TOXENV=py27-1.9-postgis
  - TOXENV=py27-1.10-sqlite
  - TOXENV=py27-1.10-postgresql
  - TOXENV=py27-1.10-postgis
  - TOXENV=py27-master-sqlite
  - TOXENV=py27-master-postgresql
  - TOXENV=py27-master-postgis
  - TOXENV=py32-1.8-sqlite
  - TOXENV=py32-1.8-postgresql
  - TOXENV=py32-1.8-postgis
  - TOXENV=py33-1.8-sqlite
  - TOXENV=py33-1.8-postgresql
  - TOXENV=py33-1.8-postgis
  - TOXENV=py34-1.8-sqlite
  - TOXENV=py34-1.8-postgresql
  - TOXENV=py34-1.8-postgis
  - TOXENV=py34-1.9-sqlite
  - TOXENV=py34-1.9-postgresql
  - TOXENV=py34-1.9-postgis
  - TOXENV=py34-1.10-sqlite
  - TOXENV=py34-1.10-postgresql
  - TOXENV=py34-1.10-postgis
  - TOXENV=py34-master-sqlite
  - TOXENV=py34-master-postgresql
  - TOXENV=py34-master-postgis

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-1.9-sqlite
    - python: 3.5
      env: TOXENV=py35-1.9-postgresql
    - python: 3.5
      env: TOXENV=py35-1.9-postgis
    - python: 3.5
      env: TOXENV=py35-1.10-sqlite
    - python: 3.5
      env: TOXENV=py35-1.10-postgresql
    - python: 3.5
      env: TOXENV=py35-1.10-postgis
    - python: 3.5
      env: TOXENV=py35-master-sqlite
    - python: 3.5
      env: TOXENV=py35-master-postgresql
    - python: 3.5
      env: TOXENV=py35-master-postgis
  allow_failures:
    - env: TOXENV=py27-master-sqlite
    - env: TOXENV=py27-master-postgresql
    - env: TOXENV=py27-master-postgis
    - env: TOXENV=py34-master-sqlite
    - env: TOXENV=py34-master-postgresql
    - env: TOXENV=py34-master-postgis
    - env: TOXENV=py35-master-sqlite
    - env: TOXENV=py35-master-postgresql
    - env: TOXENV=py35-master-postgis

install:
  - pip install tox coveralls "virtualenv<14.0"

before_script:
  - if echo $TOXENV | grep -E '(-postgresql|-postgis)' -q; then psql -U postgres -c "CREATE DATABASE mutant;"; fi
  - if echo $TOXENV | grep '\-postgis' -q; then psql mutant -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"; fi

script:
  - tox

after_success:
  - coveralls
